[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc-version = '0.8.26'
optimizer = true
optimizer-runs = 200
evm-version = 'cancun'

[rpc_endpoints]
base = '${BASE_RPC_URL}'
base_sepolia = '${BASE_SEPOLIA_RPC_URL}'

[etherscan]
base = { key = '${BASESCAN_API_KEY}' }
base_sepolia = { key = '${BASESCAN_API_KEY}' }

